version: "3"

services:
  catalog-view-api:
    image: eu.gcr.io/digdir-fdk-infra/catalog-view-api:test
    build: .
    environment:
      - MASKINPORTEN_SCOPE=test.scope
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=elasticpwd
      - ELASTIC_SSL=false
      - ELASTIC_URI=elasticsearch:9200
      - ELASTIC_KEYSTORE_PATH=keystore.jks
      - ELASTIC_KEYSTORE_PASSWORD=keystore
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
      - elasticsearch

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=elasticpwd
      - ES_JAVA_OPTS=-Xms2G -Xmx2G
